### ISSUE TITLE
FSAF 支持多通道吗

### ISSUE THREAD

**Issue by ghost** [suilin0432/FSAFHeadCodeWithComment#1]
我想使用SSD联结FSAF模块， 改变in_channels=[512, 1024, 512，256，256，256],这样子做可以实现吗？希望能够得到您的回复指导，不胜感激

**Comment by suilin0432** [comment]
没有明白什么叫SSD联结FSAF模块... 指的就是改变 feature map 的输出的通道数吗? 
这个代码作者是基于 mmdetection 修改的, mmdetection 自带的 neck 你可以看看支不支持 out_channel 可以变化, 我没有太注意.
或者 你可以看一下 mmdetection 中 SSD 是怎么做的, 这个问题应该是能解决的, 如果这个 fsaf_head 不兼容这个变化的话代码改起来应该也是很简单的. 甚至如果 SSDHead 不能兼容改起来也不会很麻烦.

PS: 另外要注意的是 这个代码作者复现的时候好像就是 anchor-free 的分支, 并没有加 anchor-based 的分支, 想要这部分的话还是要自己实现.

**Comment by Noah-CV** [comment]
嗯嗯，我是想SSD（VGG16+FPN+FSAF，但是ssd好像最后几个预测层无法+FPN，所以想直接和ssd_head一样输入六个预测层的通道数作为输入，但是发现fsaf_head好像只支持一个(256),所以现在我再尝试下修改，大佬可以加个微信吗，希望不会的可以问下，再次感谢您的回复。
我的wx：kouzics

**Comment by sunshuai95** [comment]
这位朋友实现ssd插入fsaf了吗？
